apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-git-repositories
spec:  
  # This provides users a working example of how an admin
  # would be able to enforce git repository sources across
  # all tenants.
  validationFailureAction: Audit # Change to 'Enforce' once the specific org url is set.
  rules:
    - name: github-https-only
      exclude:
        resources:
          namespaces:
            - flux-system
      match:
        any:
        - resources:
            kinds:
              - GitRepository
      validate:
        message: ".spec.url must be from a HTTP/S repository within the organisation X"
        anyPattern:
        - spec:
            url: "https://github.com/controlplaneio-fluxcd/?*" # change the org name to your specific org
