apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 48h
    target:
        kind: HelmRelease
        name: kube-prometheus-stack
