---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admission-controllers
  namespace: flux-system
spec:
  serviceAccountName: flux-infra
  dependsOn:
    - name: monitoring-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/admission/controllers/${environment:=staging}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admission-configs
  namespace: flux-system
spec:
  serviceAccountName: flux-infra
  dependsOn:
    - name: admission-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/admission/configs/${environment:=staging}
