apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    toolkit.fluxcd.io/tenant: platform-team
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    toolkit.fluxcd.io/tenant: platform-team
  name: flux-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    toolkit.fluxcd.io/tenant: platform-team
